### PR TITLE
Substituted Deleted Navmesh Messages for Nav tags

### PR DESCRIPTION
**Pull request by shadowslasher410**
MWAHAHA! My rebirth is completed... sort of, I still got a long way to go. But hey, at least it finally works! Anyway, just like it says on the tin, I deleted all the deleted navmesh messages and put nav tags in instead. for the small number of plugins that didn't have dirty data associated with them, I just deleted the message - I tried adding an alias, but loot got all spazzy on me, so I say, if they want to see their deleted navmeshs in LOOT, give us crcs!

### CODE REVIEW

**Comment by WrinklyNinja** [comment]
OK, so the website diff viewer is pretty limited, but the good news is that if I open up Git and turn my screen sideways, I can see what your changes are. Unfortunately I can't make inline comments, so I'll just reference plugin entries:

* `BertsBreezeCellar.v.1.0(esm).esm`: You removed an `*obsolete` message.
* `Lyberanthuin Restored.esp`: You changed a dirty info entry, it looks like you replaced it with one from the mod above.

I think you're right to just remove the navmesh messages for plugins without accompanying CRCs or existing dirty info, and to add the navmesh counts to existing dirty info when there aren't accompanying CRCs. 

Though the former is a loss of information, being spammed about navmeshes when they've been fixed isn't useful, and I removed a few dirty messages without CRCs when initially converting the masterlists from BOSS, so there's precedence. Adding the navmesh counts to existing dirty info may be inaccurate, but it's better than nothing, and any inaccuracies that matter will probably be reported in due course.

If you can fix the couple of problems I mentioned above, I'll be happy to merge in the first commit of this PR. However, the other two you pushed break the "one thing per PR" guideline, so they should go in a separate PR.

To do this easily, before you make the fixes, do the following:

```
git checkout -b alias-obsolete
git checkout v0.8
git reset --hard HEAD^^
git reset HEAD^
```

That'll branch off the second and third commits, then remove them from the `v0.8` branch, then undo (but keep the changes of) the first commit. You can then make the necessary fixes, commit it again, and push it to GitHub with `git push --force`, then I can merge it.

Congratulations on getting the masterlist below 1 MB! :fireworks: 

---

For the 'obsolete' message aliasing, I've got a few problems with it:

* Message anchors that use substitutions are can be named to show that: `&obsoleteUpdateAtX` is better at hinting that you've got to substitute something into it than `&obsoleteVersion`.
* Your `&AlreadyInMod` alias message doesn't make much sense as a replacement where it's used, as it doesn't match the text or intent of the messages it replaces. I'd use an `&obsoleteUpgradeToX` message for these cases, with text such as `Obsolete. Upgrade to %1%.`.
* You've removed some 'obsolete' messages without replacing with them, eg. `Murder01.esm`, `CriticalChargeFix.esp`, etc. Where they give a replacement mod's name or link, use `&obsoleteUpgradeToX` or whatever you call it instead of `&obsolete`, so the information isn't lost.

This commit (squashed with third) needs to be split into three separate commits. They can all go into the same PR, but there should be one commit for each of:

* Using more `*obsolete` aliases.
* Adding an `&obsoleteUpdateAtX` message and using it.
* Adding an `&obsoleteUpgradeToX` message and using it.

**Comment by shadowslasher410** [comment]
Okay, there's that. So I'm guessing I can have more than one pull request open at a time? Haha, I thought it was only one. Anyway, gonna get started on the obsolete messages stuff. Thanks for the help!

**Comment by WrinklyNinja** [comment]
You can have one PR for each branch you have.

**Comment by WrinklyNinja** [comment]
Looks good! :+1:

I just want to make sure that as mentioned in #67, the cleaning guide we link to is suitably updated (which I can probably do tonight), then I'll merge this.

**Pull request merged**
