### PR TITLE
Replace localised messages in prelude/common with new short definitions

### PR DESCRIPTION
**Pull request by pStyl3**
Under https://github.com/loot/loot.github.io/issues/87

Global anchors `&creationClubPlugins` as well as `&moveNVAC` have not been added, as their contents do not fit the Skyrim masterlist.

### CODE REVIEW

**Comment by pStyl3** [comment]
I'm not sure, why the validation fails. I did update prelude's `ci.yml` [here](https://github.com/loot/prelude/pull/5), but that didn't fix this validation error either. I will investigate this later and keep the PR open for now.

**Comment by sibir-ine** [comment]
I think it's just that none of the content strings are wrapped in quotes.

**Comment by pStyl3** [comment]
🤦‍♂️ 

@sibir-ine Thanks, that was it. 😄

Any other objections to this? @Ortham @MacSplody

**Comment by Ortham** [comment]
No objections from me.

**Comment by sibir-ine** [comment]
One suggestion I have is to keep subs & conditions for the short definitions. For some messages, they provide context that would be useful for contributors when deciding which anchor is appropriate in a given situation without having to look in the prelude, &, for others, they're needed to ensure the masterlists will still be valid in isolation (e.g., `&deleteOrDeactivateX` as some uses rely on it's default blank sub).

**Comment by pStyl3** [comment]
@sibir-ine Sounds reasonable. Done.

**Pull request merged**
