### PR TITLE
Removed doNotClean message from SeaPoint Settlement

### PR DESCRIPTION
**Pull request by ProbablyManuel**
This mod contains no ITMs.

### CODE REVIEW

**Comment by MacSplody** [comment]
```yaml
  - name: 'SeaPointSettlement.esp'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x0CA559AA
        util: 'TES5Edit v3.2.70 EXPERIMENTAL'
        itm: 57
    clean:
      - crc: 0x3B5252AE
        util: 'TES5Edit v3.2.70 EXPERIMENTAL'
```

You have to change your settings in xEdit. 
image

Some ITMs only show if these options are unticked.

**Comment by ProbablyManuel** [comment]
Neither TES5Edit 3.2.2 nor TES5Edit 3.2.70 Experimental show me any ITMs in SeaPointSettlement.esp with CRC 0CA559AA, even with these options unticked.

**Comment by MacSplody** [comment]
Ah yes they will only show up with simple records unticked as well.
Yeah it can be removed, as the above ITM are for NAVM.

**Review by MacSplody — CHANGES_REQUESTED** [review]
Add cleaning information instead.

```yaml
  - name: 'SeaPointSettlement.esp'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x0CA559AA
        util: 'TES5Edit v3.2.70 EXPERIMENTAL'
        itm: 57
    clean:
      - crc: 0x3B5252AE
        util: 'TES5Edit v3.2.70 EXPERIMENTAL'
```

**Comment by ProbablyManuel** [comment]
Shouldn't this option only affect how these records are displayed and not affect the cleaning process? If the binary representations are identical, the hexadecimal representations should be too.

And isn't this option enabled by default, i.e. most users won't be able to clean these ITMs unless they're told to disable this option?

**Comment by MacSplody** [comment]
There are plans to update the xEdit cleaning guide to help users with this change.
And there is an automatic cleaning which will do this for them.
-quickautoclean as a launch argument will do the cleaning for them.
image

NAVM are complex, comparing them as simple records will not show if they're ITMs.
Because the data may be the same, but it can be ordered differently.
This extra cleaning helps get rid of any noise in conflict detection between mods which change locations.

**Review by MacSplody — APPROVED** [review]

**Pull request merged**
