### PR TITLE
Rework various messages

### PR DESCRIPTION
**Pull request by DaCoolX**
Many German translations optimized and been made more clear and coherent
English messages improved
Exact duplicates from the English original in the Spanish translation have been revised
Numerous double spaces trimmed

### CODE REVIEW

**Comment by Infernio** [comment]
That whole `FNIS_SexLab_List.txt ` message can probably be removed or at least reworded. It talks about having to set `Override Skips` in BAIN, but BAIN hasn't been skipping TXT files in subfolders for... several years at this point.

Edit: Just tried installing SexLab to test it, and that TXT file gets installed just fine by all recent Wrye Bash betas (tried all releases down to 307.beta3, which was released in mid-2018).

**Comment by DaCoolX** [comment]
I haven't modded Oldrim for several years now so I wouldn't know, I mostly do translations and spell & grammar corrections. My main focus and concern was improving messages where I noticed when there was room for improvement. You are welcome to make a separate pull-request for removing anything structurally obsolete and get it merged before this PR and I would keep pace  here. In addition, edits to my branch are enabled for maintainers.

**Comment by Infernio** [comment]
I'm not a maintainer either, was just pointing it out when I noticed it :)
If I do end up removing the message, I'll wait for your PR to get merged first to avoid any merge conflicts.

**Comment by Ortham** [comment]
Thanks for also correcting some of the English messages, and removing those not-actually-Spanish messages too. 👍

**Pull request merged**
