### PR TITLE
Aliased popular messages and added string substitutions where needed

### PR DESCRIPTION
**Pull request by shadowslasher410**
Sorry the commit is so gigantic - I guess I tried to do too many things at once. ;)

I probably missed somewhere where I was supposed to string substitute but didn't... So keep your eyes peeled for stuff I missed.

The only thing left to do I think would be to finish substituting the useOnlyOneX messages in for all the entries. I started, but I haven't worked with C++ regex before, so it's a little confusing to me. Can someone check to see if I did it right, or will Travis blow up if I did it wrong? On a related note, you can regex .esp and .esm files right (for the many condition)? I just put what I thought it would be, but... I don't know. I've been staring at this too long...

### CODE REVIEW

**Comment by WrinklyNinja** [comment]
Can you please rebase this off the most recent `v0.8` branch? When you do, Travis can check validity and it can then be merged automatically.

**Comment by shadowslasher410** [comment]
Can You Help me? So, I'm debugging the masterlist, and I keep getting the "too-many-arguments" (format string refers to fewer arguments than were passed) error. How would I fix this?

**Comment by WrinklyNinja** [comment]
> Can You Help me? So, I'm debugging the masterlist, and I keep getting the "too-many-arguments" (format string refers to fewer arguments than were passed) error. How would I fix this?

That means you've got a `subs` key that has more entries than the content string has substitution placeholders.

**Comment by WrinklyNinja** [comment]
In fact, I'm rejecting this because it's so big it's impossible to review, I can't tell what you've done. Please split it up into smaller commits and more focussed pull requests (eg. a PR for each type of message aliased, maybe).

Also, a quick scan through the diff shows that your changes are riddled with syntax errors. Do a little at a time and you're much less likely to carry such mistakes through a huge body of work, because you can get each step reviewed in a PR.

**Pull request closed without merging**
