### PR TITLE
Added New Alias and String Substitutions

### PR DESCRIPTION
**Pull request by shadowslasher410**
M'kay, this just contains a new alias, AlreadyInMod and string substitutions for it.

Sorry if you get all the commits I had before, you only really need 0adca03. 

The other two was me trying to squash the previous commits (I don't think it worked) and me pulling from the remote 'cause gitshell said I couldn't push otherwise for some reason.

### CODE REVIEW

**Comment by shadowslasher410** [comment]
WTH! I didn't touch that line! Why did it fail?

**Comment by WrinklyNinja** [comment]
Travis is showing a syntax error, and you still haven't rebased off the latest `v0.8` commit - see [here](https://github.com/loot/skyrim/network) for the problem in graphical form.

I do really want to merge this, because ~ 5,000 lines cut out the masterlist is half way to my < 1 MB goal, but I can't without it getting fixed, and you're in a better position to do that than me.

**Comment by shadowslasher410** [comment]
Okay.... I put git rebase v0.8 into the gitshell, so I think I rebased it now (hopefully. Unless there's more stuff I gotta do). Oh, and I figured out what was causing the error: the entry 'Deleveled Skyrim - 3rdEraWeaponsMoS.esp' has an unescaped '-' character.

**Comment by shadowslasher410** [comment]
Damnit! Didn't work! Grr.. I'm soo tempted to just delete this fork then make another one... I think that's what i'll do.

**Pull request closed without merging**
