### PR TITLE
Bash tag changes to Update.esm and DLCs

### PR DESCRIPTION
**Pull request by Nebulous112**
This pull request changes the listed bash tags for Update.esm and the
DLCs to the bash tags Arthmoor recommended in the[ Bethsoft Wrye Bash](http://forums.bethsoft.com/topic/1604190-wrye-bash-thread-110/?p=25187088)
thread.

### CODE REVIEW

**Comment by Nebulous112** [comment]
@Arthmoor 

Care to review? Do these bash tags look correct to you?

Edit: Also, this is my first pull request ever...just tried to learn how GitHub works to pull this. I see a check has failed...what did I do wrong?

**Comment by Freso** [comment]
I don't really know anything about bash tag specifics, so I'll leave the reviewing of that to @Arthmoor or someone else. :)

> I see a check has failed...what did I do wrong?

If you look at the "Details" of the failed check/build, you'll find this error message: "ERROR: yaml-cpp: error at line 518, column 7: bad conversion: set elements must be unique". If you then look at line 518, you will find that you added `Graphics` to a list that already had `Graphics` in it. ;)

**Comment by Arthmoor** [comment]
Yes, those tags are correct.

**Comment by Nebulous112** [comment]
Whoops, I'll see if I can fix that.

**Comment by Freso** [comment]
Thanks @Nebulous112 and @Arthmoor!

**Pull request merged**
